CREATE TABLE students AS
   SELECT "7/24/2018 16:55:49" AS time, 35 AS number, "blue" AS color, "7" AS seven, "The Middle by Jimmy Eat World" as song, "7/6" as date, "cat" as pet, "Image 2" AS denero, 5 AS smallest UNION
   SELECT "7/24/2018 16:56:12", 11          , "blue"                                         , "the number 7 below."       , "Bohemian Rhapsody"      , "5/18" , "golden retriever, i like dogs"                                                                                                                                     , "Image 3", 5      UNION
   SELECT "7/24/2018 16:57:31", 51          , "pink"                                         , "Choose this option instead", "The Middle"             , "5/1"  , "bird "                                                                                                                                                             , "Image 5", 15     UNION
   SELECT "7/24/2018 17:01:36", 21          , "turquoise"                                    , "You're not the boss of me!", "Fur Elise"              , "3/20" , "tiger"                                                                                                                                                             , "Image 5", 2147483647  UNION
   SELECT "7/24/2018 17:55:11", 7           , "pink"                                         , "the number 7 below."       , "You Belong With Me"     , "11/21", "baby panda"                                                                                                                                                        , "Image 4", 7      UNION
   SELECT "7/24/2018 17:55:28", 5           , "blue"                                         , "Choose this option instead", "Fur Elise"              , "3/12" , "killer whale"                                                                                                                                                      , "Image 4", 1      UNION
   SELECT "7/24/2018 17:55:29", 87          , "pink"                                         , "the number 7 below."       , "You Belong With Me"     , "12/10", "myself"                                                                                                                                                            , "Image 4", 7      UNION
   SELECT "7/24/2018 17:55:43", 23          , "blue"                                         , "7"                         , "God's Plan"             , "10/1" , "lemur"                                                                                                                                                             , "Image 3", 1      UNION
   SELECT "7/24/2018 17:55:45", 23          , "pastel blue"                                  , "the number 7 below."       , "God's Plan"             , "2/23" , "dinosaur"                                                                                                                                                          , "Image 5", 11     UNION
   SELECT "7/24/2018 17:55:45", 66          , "red"                                          , "Choose this option instead", "Bohemian Rhapsody"      , "6/6"  , "dog"                                                                                                                                                               , "Image 2", 24     UNION
   SELECT "7/24/2018 17:56:02", 42          , "blue"                                         , "the number 7 below."       , "The Middle"             , "12/4" , "tiger"                                                                                                                                                             , "Image 3", 1      UNION
   SELECT "7/24/2018 17:56:20", 42          , "green"                                        , "Choose this option instead", "The Middle"             , "4/20" , "sloth"                                                                                                                                                             , "Image 5", 47     UNION
   SELECT "7/24/2018 17:56:37", 8           , "blue"                                         , "the number 7 below."       , "Bohemian Rhapsody"      , "10/8" , "dog"                                                                                                                                                               , "Image 3", 7      UNION
   SELECT "7/24/2018 17:57:03", 43          , "grey"                                         , "7"                         , "The Middle"             , "10/20", "great pyrenees"                                                                                                                                                    , "Image 4", 1      UNION
   SELECT "7/24/2018 17:57:58", 50          , "purple"                                       , "7"                         , "You Belong With Me"     , "12/25", "rabbit"                                                                                                                                                            , "Image 5", 1      UNION
   SELECT "7/24/2018 17:58:10", 12          , "yellow"                                       , "7"                         , "Bohemian Rhapsody"      , "8/12" , "lion"                                                                                                                                                              , "Image 3", 7      UNION
   SELECT "7/24/2018 17:58:43", 22          , "purple"                                       , "Choose this option instead", "Bohemian Rhapsody"      , "11/22", "dire wolf"                                                                                                                                                         , "Image 5", 22     UNION
   SELECT "7/24/2018 17:58:51", 13          , "violet"                                       , "7"                         , "God's Plan"             , "4/20" , "tiger"                                                                                                                                                             , "Image 5", 14     UNION
   SELECT "7/24/2018 17:58:56", 13          , "gray"                                         , "Choose this option instead", "Everytime We Touch"     , "8/11" , "human"                                                                                                                                                             , "Image 3", 1      UNION
   SELECT "7/24/2018 18:02:53", 97          , "blue"                                         , "You're not the boss of me!", "Everytime We Touch"     , "6/16" , "denero"                                                                                                                                                            , "Image 1", 1      UNION
   SELECT "7/24/2018 18:03:33", 25          , "white"                                        , "7"                         , "Down With The Sickness" , "10/20", "tarantula"                                                                                                                                                         , "Image 4", 3      UNION
   SELECT "7/24/2018 18:04:40", 42          , "blue"                                         , "Choose this option instead", "Bohemian Rhapsody"      , "1/23" , "eagle"                                                                                                                                                             , "Image 5", 8      UNION
   SELECT "7/24/2018 18:05:07", 33          , "orange"                                       , "7"                         , "Fur Elise"              , "10/31", "mountain lion"                                                                                                                                                     , "Image 2", 37     UNION
   SELECT "7/24/2018 18:05:57", 18          , "blue"                                         , "7"                         , "Bohemian Rhapsody"      , "12/25", "pig"                                                                                                                                                               , "Image 5", 11     UNION
   SELECT "7/24/2018 18:08:00", 5           , "blue"                                         , "Choose this option instead", "Bohemian Rhapsody"      , "1/30" , "tiger"                                                                                                                                                             , "Image 1", 23     UNION
   SELECT "7/24/2018 18:08:49", 24          , "blue (crip nation)"                           , "the number 7 below."       , "Fur Elise"              , "9/11" , "alpaca"                                                                                                                                                            , "Image 2", 21     UNION
   SELECT "7/24/2018 18:09:12", 12          , "color of pain"                                , "the number 7 below."       , "God's Plan"             , "4/20" , "kanye west"                                                                                                                                                        , "Image 5", 420    UNION
   SELECT "7/24/2018 18:09:15", 69          , "red"                                          , "7"                         , "Down With The Sickness" , "9/11" , "monkey"                                                                                                                                                            , "Image 1", 19     UNION
   SELECT "7/24/2018 18:09:54", 3           , "blue"                                         , "You're not the boss of me!", "The Middle"             , "7/15" , "doraemon"                                                                                                                                                          , "Image 3", 3      UNION
   SELECT "7/24/2018 18:12:16", 69          , "seabreeze"                                    , "seven"                     , "Bohemian Rhapsody"      , "12/31", "sloth"                                                                                                                                                             , "Image 2", 7      UNION
   SELECT "7/24/2018 18:13:11", 4           , "blue"                                         , "7"                         , "Everytime We Touch"     , "6/13" , "hippo"                                                                                                                                                             , "Image 3", 3      UNION
   SELECT "7/24/2018 18:14:55", 96          , "green"                                        , "7"                         , "Fur Elise"              , "10/10", "orca"                                                                                                                                                              , "Image 3", 112    UNION
   SELECT "7/24/2018 18:14:55", 37          , "white"                                        , "You're not the boss of me!", "Fur Elise"              , "6/6"  , "hydra"                                                                                                                                                             , "Image 2", 38     UNION
   SELECT "7/24/2018 18:15:22", 11          , "dark blue "                                   , "Choose this option instead", "God's Plan"             , "2/29" , "dragon "                                                                                                                                                           , "Image 5", 11     UNION
   SELECT "7/24/2018 18:16:42", 1           , "blue"                                         , "seven"                     , "God's Plan"             , "5/11" , "dolphin"                                                                                                                                                           , "Image 4", 53     UNION
   SELECT "7/24/2018 18:18:47", 16          , "navy blue"                                    , "the number 7 below."       , "Fur Elise"              , "1/16" , "cat"                                                                                                                                                               , "Image 3", 1      UNION
   SELECT "7/24/2018 18:21:03", 13          , "blue"                                         , "You're not the boss of me!", "Bohemian Rhapsody"      , "2/29" , "penguin"                                                                                                                                                           , "Image 2", 18184526549  UNION
   SELECT "7/24/2018 18:22:23", 7           , "sky blue"                                     , "You're not the boss of me!", "Fur Elise"              , "1/17" , "cat"                                                                                                                                                               , "Image 3", 1      UNION
   SELECT "7/24/2018 18:28:51", 7           , "red"                                          , "7"                         , "God's Plan"             , "12/25", "dog"                                                                                                                                                               , "Image 2", 7      UNION
   SELECT "7/24/2018 18:32:19", 99.999      , "black"                                        , "You're not the boss of me!", "Bohemian Rhapsody"      , "2/29" , "panda！"                                                                                                                                                            , "Image 5", 18     UNION
   SELECT "7/24/2018 18:32:28", 69          , "blue"                                         , "seven"                     , "Bohemian Rhapsody"      , "6/15" , "dog to a white person"                                                                                                                                             , "Image 2", 6      UNION
   SELECT "7/24/2018 18:35:22", 92          , "green"                                        , "7"                         , "Fur Elise"              , "4/29" , "a small triceratops "                                                                                                                                              , "Image 2", 8      UNION
   SELECT "7/24/2018 18:35:41", 44          , "blue"                                         , "You're not the boss of me!", "Fur Elise"              , "4/4"  , "hachi from the movie"                                                                                                                                              , "Image 4", 4      UNION
   SELECT "7/24/2018 18:37:48", 99          , "blue. no yello-- auuuuuuuugh!"                , "the number 7 below."       , "Fur Elise"              , "4/20" , "human"                                                                                                                                                             , "Image 2", 1      UNION
   SELECT "7/24/2018 18:40:16", 9           , "green"                                        , "seven"                     , "Everytime We Touch"     , "1/1"  , "dog"                                                                                                                                                               , "Image 2", 4      UNION
   SELECT "7/24/2018 18:42:44", 17          , "indigo"                                       , "7"                         , "Bohemian Rhapsody"      , "8/2"  , "doggo"                                                                                                                                                             , "Image 2", 29     UNION
   SELECT "7/24/2018 18:46:27", 6           , "black"                                        , "Choose this option instead", "God's Plan"             , "1/19" , "corgi"                                                                                                                                                             , "Image 4", 3      UNION
   SELECT "7/24/2018 18:54:51", 8           , "red"                                          , "seven"                     , "Bohemian Rhapsody"      , "9/8"  , "t-rex"                                                                                                                                                             , "Image 5", 1      UNION
   SELECT "7/24/2018 18:55:57", 69          , "green"                                        , "Choose this option instead", "Bohemian Rhapsody"      , "1/1"  , "giraffe"                                                                                                                                                           , "Image 1", 19     UNION
   SELECT "7/24/2018 19:11:54", 33          , "blue"                                         , "Choose this option instead", "Bohemian Rhapsody"      , "3/3"  , "eevee"                                                                                                                                                             , "Image 2", 2      UNION
   SELECT "7/24/2018 19:18:35", 66          , "green"                                        , "the number 7 below."       , "Fur Elise"              , "10/1" , "dog"                                                                                                                                                               , "Image 4", 19     UNION
   SELECT "7/24/2018 19:18:44", 32          , "blue"                                         , "You're not the boss of me!", "You Belong With Me"     , "1/23" , "dog"                                                                                                                                                               , "Image 3", 47     UNION
   SELECT "7/24/2018 19:19:01", 3.141592654 , "blue"                                         , "the number 7 below."       , "God's Plan"             , "12/26", "dinosaur"                                                                                                                                                          , "Image 2", 23     UNION
   SELECT "7/24/2018 19:19:15", 22          , "green"                                        , "Choose this option instead", "You Belong With Me"     , "5/4"  , "turtle"                                                                                                                                                            , "Image 1", 6      UNION
   SELECT "7/24/2018 19:20:17", 69          , "grey"                                         , "7"                         , "God's Plan"             , "6/9"  , "doge"                                                                                                                                                              , "Image 3", 68     UNION
   SELECT "7/24/2018 19:23:23", 69          , "blue"                                         , "7"                         , "You Belong With Me"     , "1/1"  , "elephant"                                                                                                                                                          , "Image 4", 17     UNION
   SELECT "7/24/2018 19:24:22", 27          , "gray"                                         , "the number 7 below."       , "Bohemian Rhapsody"      , "9/3"  , "chimpanzee"                                                                                                                                                        , "Image 2", 16     UNION
   SELECT "7/24/2018 19:27:40", 69          , "blue and gold go bears!"                      , "7"                         , "Everytime We Touch"     , "4/20" , "small dog"                                                                                                                                                         , "Image 1", 14     UNION
   SELECT "7/24/2018 19:31:55", 3           , "red"                                          , "Choose this option instead", "You Belong With Me"     , "11/1" , "corgi"                                                                                                                                                             , "Image 5", 3      UNION
   SELECT "7/24/2018 19:32:11", 77          , "navy blue"                                    , "the number 7 below."       , "Bohemian Rhapsody"      , "2/7"  , "white tiger"                                                                                                                                                       , "Image 3", 26     UNION
   SELECT "7/24/2018 19:37:39", 77          , "black"                                        , "the number 7 below."       , "Down With The Sickness" , "8/26" , "unicorn"                                                                                                                                                           , "Image 5", 31     UNION
   SELECT "7/24/2018 19:44:47", 4           , "mint green"                                   , "7"                         , "Bohemian Rhapsody"      , "10/1" , "red panda"                                                                                                                                                         , "Image 3", 1      UNION
   SELECT "7/24/2018 19:44:52", 1           , "the green in my broccoli and chicken penne"   , "Choose this option instead", "Fur Elise"              , "12/25", "james, tammy, jen, mitas"                                                                                                                                          , "Image 2", 32     UNION
   SELECT "7/24/2018 19:46:52", 69          , "green"                                        , "7"                         , "God's Plan"             , "4/20" , "common housecat"                                                                                                                                                   , "Image 2", 42069  UNION
   SELECT "7/24/2018 19:51:28", 72          , "maroon"                                       , "7"                         , "Fur Elise"              , "4/27" , "standard poodle"                                                                                                                                                   , "Image 3", 11     UNION
   SELECT "7/24/2018 19:54:25", 26          , "pink"                                         , "the number 7 below."       , "You Belong With Me"     , "9/26" , "cat"                                                                                                                                                               , "Image 5", 23     UNION
   SELECT "7/24/2018 19:55:35", 66          , "ref"                                          , "the number 7 below."       , "You Belong With Me"     , "3/7"  , "dog！"                                                                                                                                                              , "Image 3", 27     UNION
   SELECT "7/24/2018 20:04:56", 66          , "blue"                                         , "You're not the boss of me!", "The Middle"             , "7/12" , "a dog"                                                                                                                                                             , "Image 4", 3      UNION
   SELECT "7/24/2018 20:05:35", 77          , "blackpink"                                    , "Choose this option instead", "Everytime We Touch"     , "8/15" , "human"                                                                                                                                                             , "Image 1", 17     UNION
   SELECT "7/24/2018 20:11:09", 21          , "purple"                                       , "Choose this option instead", "Bohemian Rhapsody"      , "7/24" , "chickens"                                                                                                                                                          , "Image 4", 89     UNION
   SELECT "7/24/2018 20:21:55", 11          , "purple"                                       , "the number 7 below."       , "You Belong With Me"     , "9/25" , "panda"                                                                                                                                                             , "Image 1", 1      UNION
   SELECT "7/24/2018 20:26:34", 77          , "blue"                                         , "7"                         , "God's Plan"             , "9/22" , "something cuddly"                                                                                                                                                  , "Image 2", 36     UNION
   SELECT "7/24/2018 20:30:22", 12          , "blue"                                         , "the number 7 below."       , "Everytime We Touch"     , "3/29" , "dolphin"                                                                                                                                                           , "Image 3", 1      UNION
   SELECT "7/24/2018 20:37:13", 18          , "green"                                        , "the number 7 below."       , "Fur Elise"              , "9/18" , "dog"                                                                                                                                                               , "Image 4", 18     UNION
   SELECT "7/24/2018 20:38:40", 75          , "mikado"                                       , "the number 7 below."       , "Fur Elise"              , "8/9"  , "dog"                                                                                                                                                               , "Image 4", 22     UNION
   SELECT "7/24/2018 20:41:20", 1           , "i am a cool guy, so i like blue"              , "You're not the boss of me!", "God's Plan"             , "2/29" , "an african elephant"                                                                                                                                               , "Image 2", 70924835987094798237947509823745987029875903847509287435092879458273059748957903284758902379587239579032874509823795879073491628976893765982736458726398456283764587263875469283476598374  UNION
   SELECT "7/24/2018 20:52:25", 1           , "teal"                                         , "the number 7 below."       , "Everytime We Touch"     , "1/23" , "axolotl"                                                                                                                                                           , "Image 1", 161803398875  UNION
   SELECT "7/24/2018 20:53:11", 50          , "white"                                        , "the number 7 below."       , "Bohemian Rhapsody"      , "11/7" , "dog"                                                                                                                                                               , "Image 2", 1      UNION
   SELECT "7/24/2018 20:58:24", 13          , "pink"                                         , "the number 7 below."       , "Everytime We Touch"     , "1/8"  , "cat"                                                                                                                                                               , "Image 2", 1      UNION
   SELECT "7/24/2018 21:01:28", 9           , "blue"                                         , "7"                         , "God's Plan"             , "9/27" , "an immortal dog in good health"                                                                                                                                    , "Image 2", 1      UNION
   SELECT "7/24/2018 21:03:51", 42          , "blue"                                         , "the number 7 below."       , "You Belong With Me"     , "8/29" , "panda"                                                                                                                                                             , "Image 3", 42     UNION
   SELECT "7/24/2018 21:07:42", 42          , "hot pink "                                    , "the number 7 below."       , "Everytime We Touch"     , "10/31", "a bat"                                                                                                                                                             , "Image 2", 35     UNION
   SELECT "7/24/2018 21:12:33", 23          , "grey"                                         , "You're not the boss of me!", "Down With The Sickness" , "10/13", "dolphin"                                                                                                                                                           , "Image 2", 13     UNION
   SELECT "7/24/2018 21:16:36", 11          , "blue"                                         , "the number 7 below."       , "Bohemian Rhapsody"      , "12/1" , "red panda"                                                                                                                                                         , "Image 3", 14     UNION
   SELECT "7/24/2018 22:23:59", 20          , "lavender"                                     , "seven"                     , "Bohemian Rhapsody"      , "12/1" , "polar bear cub"                                                                                                                                                    , "Image 3", 3      UNION
   SELECT "7/24/2018 22:28:01", 8           , "gray"                                         , "the number 7 below."       , "Bohemian Rhapsody"      , "12/25", "phoenix"                                                                                                                                                           , "Image 4", 1      UNION
   SELECT "7/24/2018 22:33:18", 13          , "black"                                        , "You're not the boss of me!", "God's Plan"             , "7/11" , "elephant"                                                                                                                                                          , "Image 1", 1      UNION
   SELECT "7/24/2018 22:42:01", 77          , "azure"                                        , "the number 7 below."       , "You Belong With Me"     , "6/1"  , "doge"                                                                                                                                                              , "Image 1", 33     UNION
   SELECT "7/24/2018 22:43:02", 42          , "white"                                        , "7"                         , "Bohemian Rhapsody"      , "12/24", "cat"                                                                                                                                                               , "Image 4", 34     UNION
   SELECT "7/24/2018 22:49:21", 3           , "blue"                                         , "7"                         , "God's Plan"             , "1/1"  , "a german shepherd"                                                                                                                                                 , "Image 1", 1      UNION
   SELECT "7/24/2018 22:51:39", 69          , "yellow"                                       , "the number 7 below."       , "God's Plan"             , "4/1"  , "koala"                                                                                                                                                             , "Image 5", 2147483647  UNION
   SELECT "7/24/2018 22:53:50", 2           , "orange"                                       , "7"                         , "Bohemian Rhapsody"      , "11/6" , "tiger "                                                                                                                                                            , "Image 5", 3      UNION
   SELECT "7/24/2018 23:10:48", 6           , "blue"                                         , "7"                         , "God's Plan"             , "10/18", "tiger"                                                                                                                                                             , "Image 3", 1      UNION
   SELECT "7/24/2018 23:58:30", 69          , "blue"                                         , "the number 7 below."       , "Everytime We Touch"     , "9/28" , "appa from avatar"                                                                                                                                                  , "Image 4", 14     UNION
   SELECT "7/25/2018 0:13:52" , 1           , "ash grey"                                     , "Choose this option instead", "Bohemian Rhapsody"      , "7/11" , "cat"                                                                                                                                                               , "Image 1", 11     UNION
   SELECT "7/25/2018 0:37:35" , 69          , "gray"                                         , "the number 7 below."       , "Fur Elise"              , "1/1"  , "cat"                                                                                                                                                               , "Image 2", 19     UNION
   SELECT "7/25/2018 0:45:00" , 53          , "crimson"                                      , "the number 7 below."       , "You Belong With Me"     , "7/28" , "baby kangaroo"                                                                                                                                                     , "Image 4", 23     UNION
   SELECT "7/25/2018 0:50:53" , 21          , "red"                                          , "7"                         , "God's Plan"             , "1/26" , "great white"                                                                                                                                                       , "Image 1", 2      UNION
   SELECT "7/25/2018 1:08:51" , 16          , "blue"                                         , "the number 7 below."       , "The Middle"             , "4/8"  , "red panda"                                                                                                                                                         , "Image 4", 6      UNION
   SELECT "7/25/2018 1:09:27" , 27          , "black"                                        , "the number 7 below."       , "Fur Elise"              , "4/20" , "pony"                                                                                                                                                              , "Image 2", 34     UNION
   SELECT "7/25/2018 1:41:00" , 48          , "red"                                          , "the number 7 below."       , "Fur Elise"              , "2/29" , "hippopotamus"                                                                                                                                                      , "Image 3", 1      UNION
   SELECT "7/25/2018 2:12:26" , 42          , "yellow"                                       , "You're not the boss of me!", "Everytime We Touch"     , "7/23" , "human"                                                                                                                                                             , "Image 1", 32     UNION
   SELECT "7/25/2018 8:17:05" , 88          , "green"                                        , "7"                         , "The Middle"             , "12/1" , "dog"                                                                                                                                                               , "Image 2", 23     UNION
   SELECT "7/25/2018 8:39:18" , 13          , "red"                                          , "the number 7 below."       , "Bohemian Rhapsody"      , "2/7"  , "truman"                                                                                                                                                            , "Image 4", 7      UNION
   SELECT "7/25/2018 9:29:21" , 13          , "pink"                                         , "You're not the boss of me!", "God's Plan"             , "6/22" , "dog"                                                                                                                                                               , "Image 2", 1      UNION
   SELECT "7/25/2018 10:14:26", 88          , "purple"                                       , "You're not the boss of me!", "Everytime We Touch"     , "2/11" , "guinea pig"                                                                                                                                                        , "Image 3", 1      UNION
   SELECT "7/25/2018 10:24:48", 99          , "blue"                                         , "the number 7 below."       , "You Belong With Me"     , "2/12" , "shark"                                                                                                                                                             , "Image 4", 1      UNION
   SELECT "7/25/2018 10:32:10", 55          , "red"                                          , "7"                         , "Bohemian Rhapsody"      , "7/21" , "horse"                                                                                                                                                             , "Image 3", 33     UNION
   SELECT "7/25/2018 11:13:27", 77          , "blue"                                         , "the number 7 below."       , "God's Plan"             , "6/15" , "puffin"                                                                                                                                                            , "Image 2", 4      UNION
   SELECT "7/25/2018 11:13:44", 13          , "yellow"                                       , "7"                         , "Everytime We Touch"     , "5/21" , "owl"                                                                                                                                                               , "Image 5", 9      UNION
   SELECT "7/25/2018 11:14:04", 7           , "red"                                          , "7"                         , "Bohemian Rhapsody"      , "11/11", "dolphin"                                                                                                                                                           , "Image 5", 11     UNION
   SELECT "7/25/2018 11:14:07", 16          , "blue"                                         , "You're not the boss of me!", "Bohemian Rhapsody"      , "1/18" , "chinchilla"                                                                                                                                                        , "Image 5", 18     UNION
   SELECT "7/25/2018 11:17:22", 28          , "mint green"                                   , "7"                         , "You Belong With Me"     , "7/28" , "cat"                                                                                                                                                               , "Image 1", 8      UNION
   SELECT "7/25/2018 11:20:28", 85          , "orange"                                       , "the number 7 below."       , "Everytime We Touch"     , "7/7"  , "cat"                                                                                                                                                               , "Image 5", 26     UNION
   SELECT "7/25/2018 11:24:51", 68          , "black"                                        , "the number 7 below."       , "God's Plan"             , "12/25", "fish"                                                                                                                                                              , "Image 3", 698    UNION
   SELECT "7/25/2018 11:26:56", 42          , "blue"                                         , "seven"                     , "Bohemian Rhapsody"      , "4/20" , "dog."                                                                                                                                                              , "Image 3", 14     UNION
   SELECT "7/25/2018 11:45:14", 77          , "green"                                        , "7"                         , "Everytime We Touch"     , "3/31" , "dog"                                                                                                                                                               , "Image 1", 29     UNION
   SELECT "7/25/2018 12:15:46", 7           , "purple"                                       , "the number 7 below."       , "You Belong With Me"     , "7/10" , "dog"                                                                                                                                                               , "Image 4", 7      UNION
   SELECT "7/25/2018 12:24:41", 3           , "blaxk"                                        , "7"                         , "God's Plan"             , "5/28" , "dug"                                                                                                                                                               , "Image 2", 58     UNION
   SELECT "7/25/2018 12:47:09", 99          , "cerulean"                                     , "the number 7 below."       , "Everytime We Touch"     , "12/31", "maine coon"                                                                                                                                                        , "Image 4", 23     UNION
   SELECT "7/25/2018 12:57:02", 17          , "green"                                        , "7"                         , "Fur Elise"              , "1/23" , "brittishfold cat"                                                                                                                                                  , "Image 2", 44     UNION
   SELECT "7/25/2018 13:11:41", 7           , "blue"                                         , "seven"                     , "Fur Elise"              , "10/21", "pangolin"                                                                                                                                                          , "Image 5", 7      UNION
   SELECT "7/25/2018 13:20:26", 24          , "black"                                        , "the number 7 below."       , "Fur Elise"              , "2/29" , "penguin"                                                                                                                                                           , "Image 3", 1      UNION
   SELECT "7/25/2018 13:36:25", 54          , "red"                                          , "the number 7 below."       , "Bohemian Rhapsody"      , "6/23" , "dog"                                                                                                                                                               , "Image 5", 1      UNION
   SELECT "7/25/2018 13:48:12", 67          , "black"                                        , "the number 7 below."       , "You Belong With Me"     , "9/16" , "a cat"                                                                                                                                                             , "Image 3", 27     UNION
   SELECT "7/25/2018 16:06:32", 8           , "red"                                          , "7"                         , "You Belong With Me"     , "1/1"  , "dog"                                                                                                                                                               , "Image 3", 7      UNION
   SELECT "7/25/2018 16:14:12", 24          , "yellow"                                       , "7"                         , "You Belong With Me"     , "4/27" , "tiger"                                                                                                                                                             , "Image 4", 20     UNION
   SELECT "7/25/2018 19:29:20", 2           , "green"                                        , "7"                         , "The Middle"             , "4/20" , "dog"                                                                                                                                                               , "Image 4", 18     UNION
   SELECT "7/25/2018 20:21:35", 16          , "blue"                                         , "7"                         , "You Belong With Me"     , "11/23", "dolphin "                                                                                                                                                          , "Image 3", 7      UNION
   SELECT "7/25/2018 21:00:42", 99          , "blue"                                         , "seven"                     , "You Belong With Me"     , "12/27", "blobfish"                                                                                                                                                          , "Image 3", 9      UNION
   SELECT "7/25/2018 21:27:51", 97          , "white"                                        , "the number 7 below."       , "Bohemian Rhapsody"      , "12/25", "cat"                                                                                                                                                               , "Image 1", 22     UNION
   SELECT "7/25/2018 22:52:08", 15          , "shrek's skin"                                 , "the number 7 below."       , "Bohemian Rhapsody"      , "4/20" , "otter"                                                                                                                                                             , "Image 2", 11     UNION
   SELECT "7/26/2018 2:32:13" , 64          , "blue"                                         , "seven"                     , "The Middle"             , "6/6"  , "pony"                                                                                                                                                              , "Image 4", 4      UNION
   SELECT "7/26/2018 9:56:55" , 18          , "purple"                                       , "the number 7 below."       , "Bohemian Rhapsody"      , "4/20" , "pangolin"                                                                                                                                                          , "Image 4", 23     UNION
   SELECT "7/26/2018 10:02:57", 17          , "white"                                        , "the number 7 below."       , "You Belong With Me"     , "10/15", "millions!!!"                                                                                                                                                       , "Image 4", 1      UNION
   SELECT "7/26/2018 10:05:29", 99          , "blue"                                         , "the number 7 below."       , "Everytime We Touch"     , "8/2"  , "a tiger"                                                                                                                                                           , "Image 4", 74     UNION
   SELECT "7/26/2018 10:10:34", 87          , "red"                                          , "You're not the boss of me!", "God's Plan"             , "1/1"  , "a human"                                                                                                                                                           , "Image 4", 6      UNION
   SELECT "7/26/2018 11:13:39", 13          , "yellow"                                       , "7"                         , "Bohemian Rhapsody"      , "2/19" , "shiba inu"                                                                                                                                                         , "Image 1", 7      UNION
   SELECT "7/26/2018 11:14:26", 13          , "blue"                                         , "the number 7 below."       , "Bohemian Rhapsody"      , "5/24" , "komodo dragon"                                                                                                                                                     , "Image 5", 7      UNION
   SELECT "7/26/2018 11:14:31", 67          , "red"                                          , "Choose this option instead", "Bohemian Rhapsody"      , "4/13" , "capybara"                                                                                                                                                          , "Image 5", 21     UNION
   SELECT "7/26/2018 11:14:33", 42          , "silver"                                       , "You're not the boss of me!", "Bohemian Rhapsody"      , "6/8"  , "axolotl"                                                                                                                                                           , "Image 5", 34     UNION
   SELECT "7/26/2018 11:14:33", 33          , "blue"                                         , "the number 7 below."       , "God's Plan"             , "3/5"  , "dog"                                                                                                                                                               , "Image 3", 97     UNION
   SELECT "7/26/2018 11:14:37", 7           , "blue "                                        , "You're not the boss of me!", "Fur Elise"              , "5/5"  , "a phoenix"                                                                                                                                                         , "Image 3", 1      UNION
   SELECT "7/26/2018 11:14:40", 16          , "green"                                        , "Choose this option instead", "Bohemian Rhapsody"      , "3/17" , "polar bear"                                                                                                                                                        , "Image 5", 12     UNION
   SELECT "7/26/2018 11:15:11", 69          , "red"                                          , "Choose this option instead", "God's Plan"             , "2/24" , "doge"                                                                                                                                                              , "Image 3", 1      UNION
   SELECT "7/26/2018 11:15:53", 14          , "dark white "                                  , "the number 7 below."       , "Bohemian Rhapsody"      , "7/16" , "octopus "                                                                                                                                                          , "Image 5", 1      UNION
   SELECT "7/26/2018 11:16:08", 2           , "navy"                                         , "Choose this option instead", "Fur Elise"              , "12/25", "dog"                                                                                                                                                               , "Image 2", 13     UNION
   SELECT "7/26/2018 11:17:05", 99          , "ash"                                          , "the number 7 below."       , "God's Plan"             , "3/25" , "pygmy three-toed sloth"                                                                                                                                            , "Image 3", 7      UNION
   SELECT "7/26/2018 11:21:16", 28          , "violet"                                       , "the number 7 below."       , "Everytime We Touch"     , "12/28", "panda"                                                                                                                                                             , "Image 5", 4      UNION
   SELECT "7/26/2018 11:36:00", 1           , "red"                                          , "Choose this option instead", "Bohemian Rhapsody"      , "4/2"  , "cat"                                                                                                                                                               , "Image 2", 11     UNION
   SELECT "7/26/2018 12:49:17", 36          , "blue"                                         , "7"                         , "You Belong With Me"     , "3/15" , "dog!!!!"                                                                                                                                                           , "Image 4", 12     UNION
   SELECT "7/26/2018 12:52:42", 69          , "teal"                                         , "7"                         , "Fur Elise"              , "2/29" , "golden retriever"                                                                                                                                                  , "Image 4", 26     UNION
   SELECT "7/26/2018 13:36:03", 22          , "blue"                                         , "7"                         , "Bohemian Rhapsody"      , "4/20" , "doge"                                                                                                                                                              , "Image 1", 87     UNION
   SELECT "7/26/2018 16:14:57", 11          , "red"                                          , "7"                         , "Fur Elise"              , "1/1"  , "cat"                                                                                                                                                               , "Image 3", 1      UNION
   SELECT "7/26/2018 16:43:16", 42          , "grey"                                         , "Choose this option instead", "Bohemian Rhapsody"      , "3/14" , "space dragon"                                                                                                                                                      , "Image 5", 39     UNION
   SELECT "7/26/2018 17:01:17", 13          , "purple"                                       , "You're not the boss of me!", "Bohemian Rhapsody"      , "1/1"  , "octopus"                                                                                                                                                           , "Image 2", 1      UNION
   SELECT "7/26/2018 18:05:51", 15          , "navy blue"                                    , "Choose this option instead", "Fur Elise"              , "1/15" , "kangaroo"                                                                                                                                                          , "Image 4", 1      UNION
   SELECT "7/26/2018 19:45:04", 11          , "blue"                                         , "Choose this option instead", "Bohemian Rhapsody"      , "11/27", "lemur"                                                                                                                                                             , "Image 1", 2      UNION
   SELECT "7/26/2018 22:16:58", 13          , "purple"                                       , "the number 7 below."       , "You Belong With Me"     , "6/13" , "cat"                                                                                                                                                               , "Image 3", 1      UNION
   SELECT "7/26/2018 22:19:25", 96          , "red"                                          , "7"                         , "Bohemian Rhapsody"      , "10/12", "an axolotl or a cool lizard of some sort, maybe a dog"                                                                                                             , "Image 5", 1      UNION
   SELECT "7/27/2018 11:10:29", 21          , "blue"                                         , "the number 7 below."       , "Down With The Sickness" , "11/25", "doggo"                                                                                                                                                             , "Image 1", 32     UNION
   SELECT "7/27/2018 14:35:52", 17          , "gray"                                         , "7"                         , "Bohemian Rhapsody"      , "3/7"  , "sloth"                                                                                                                                                             , "Image 5", 1      UNION
   SELECT "7/27/2018 18:08:55", 78          , "blue"                                         , "7"                         , "God's Plan"             , "1/23" , "dog"                                                                                                                                                               , "Image 5", 23     ;

CREATE TABLE checkboxes AS
   SELECT "7/24/2018 16:55:49" AS time, "False" AS "0", "False" AS "1", "False" AS "2", "True" AS "3", "False" AS "4", "True" AS "5", "False" AS "6", "False" AS "7", "False" AS "8", "False" AS "9", "False" AS "10", "False" AS "2018", "False" AS "9000", "False" AS "9001" UNION
   SELECT "7/24/2018 16:56:12", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "7/24/2018 16:57:31", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/24/2018 17:01:36", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/24/2018 17:55:11", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "True"  UNION
   SELECT "7/24/2018 17:55:28", "True" , "True" , "True" , "False", "False", "False", "False", "False", "False", "False", "True" , "True" , "False", "False" UNION
   SELECT "7/24/2018 17:55:29", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "7/24/2018 17:55:43", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/24/2018 17:55:45", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False" UNION
   SELECT "7/24/2018 17:55:45", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "7/24/2018 17:56:02", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "7/24/2018 17:56:20", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "False" UNION
   SELECT "7/24/2018 17:56:37", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/24/2018 17:57:03", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "True" , "True" , "False", "False" UNION
   SELECT "7/24/2018 17:57:58", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "7/24/2018 17:58:10", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "7/24/2018 17:58:43", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False" UNION
   SELECT "7/24/2018 17:58:51", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/24/2018 17:58:56", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "True" , "True"  UNION
   SELECT "7/24/2018 18:02:53", "False", "False", "False", "True" , "False", "False", "True" , "False", "False", "False", "False", "True" , "False", "True"  UNION
   SELECT "7/24/2018 18:03:33", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False" UNION
   SELECT "7/24/2018 18:04:40", "True" , "True" , "False", "True" , "False", "True" , "True" , "True" , "False", "True" , "False", "False", "True" , "True"  UNION
   SELECT "7/24/2018 18:05:07", "True" , "True" , "False", "True" , "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/24/2018 18:05:57", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "True" , "False", "False" UNION
   SELECT "7/24/2018 18:08:00", "True" , "True" , "True" , "False", "False", "False", "False", "False", "False", "False", "False", "True" , "True" , "True"  UNION
   SELECT "7/24/2018 18:08:49", "True" , "False", "False", "False", "False", "False", "False", "True" , "False", "False", "True" , "False", "False", "False" UNION
   SELECT "7/24/2018 18:09:12", "False", "True" , "True" , "True" , "False", "True" , "False", "False", "True" , "False", "False", "False", "False", "False" UNION
   SELECT "7/24/2018 18:09:15", "True" , "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "True" , "False" UNION
   SELECT "7/24/2018 18:09:54", "True" , "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/24/2018 18:12:16", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/24/2018 18:13:11", "False", "True" , "True" , "True" , "True" , "False", "False", "False", "False", "True" , "True" , "False", "False", "False" UNION
   SELECT "7/24/2018 18:14:55", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False" UNION
   SELECT "7/24/2018 18:14:55", "True" , "False", "False", "False", "True" , "False", "False", "True" , "False", "False", "True" , "False", "False", "True"  UNION
   SELECT "7/24/2018 18:15:22", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "False", "True" , "True" , "False" UNION
   SELECT "7/24/2018 18:16:42", "False", "True" , "False", "False", "False", "True" , "True" , "False", "False", "False", "True" , "False", "False", "True"  UNION
   SELECT "7/24/2018 18:18:47", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False" UNION
   SELECT "7/24/2018 18:21:03", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "7/24/2018 18:22:23", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/24/2018 18:28:51", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/24/2018 18:32:19", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "7/24/2018 18:32:28", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/24/2018 18:35:22", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "7/24/2018 18:35:41", "False", "False", "True" , "False", "False", "True" , "False", "False", "True" , "False", "False", "False", "True" , "False" UNION
   SELECT "7/24/2018 18:37:48", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/24/2018 18:40:16", "True" , "False", "False", "True" , "False", "False", "False", "True" , "False", "True" , "False", "False", "False", "True"  UNION
   SELECT "7/24/2018 18:42:44", "False", "False", "False", "False", "False", "False", "True" , "True" , "True" , "True" , "False", "False", "False", "True"  UNION
   SELECT "7/24/2018 18:46:27", "True" , "True" , "False", "True" , "False", "False", "True" , "False", "False", "True" , "False", "False", "False", "True"  UNION
   SELECT "7/24/2018 18:54:51", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False" UNION
   SELECT "7/24/2018 18:55:57", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/24/2018 19:11:54", "False", "False", "True" , "True" , "False", "True" , "False", "True" , "False", "False", "False", "False", "False", "True"  UNION
   SELECT "7/24/2018 19:18:35", "False", "True" , "False", "False", "False", "False", "True" , "False", "False", "False", "False", "True" , "True" , "True"  UNION
   SELECT "7/24/2018 19:18:44", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/24/2018 19:19:01", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "True" , "False", "False", "False", "False" UNION
   SELECT "7/24/2018 19:19:15", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/24/2018 19:20:17", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "True" , "False", "False", "False", "False" UNION
   SELECT "7/24/2018 19:23:23", "True" , "False", "True" , "False", "False", "True" , "False", "True" , "False", "False", "False", "True" , "False", "True"  UNION
   SELECT "7/24/2018 19:24:22", "True" , "True" , "True" , "False", "False", "False", "False", "False", "False", "True" , "False", "True" , "False", "False" UNION
   SELECT "7/24/2018 19:27:40", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/24/2018 19:31:55", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/24/2018 19:32:11", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "True" , "False", "True"  UNION
   SELECT "7/24/2018 19:37:39", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "7/24/2018 19:44:47", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "7/24/2018 19:44:52", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/24/2018 19:46:52", "True" , "False", "True" , "False", "True" , "False", "True" , "False", "False", "True" , "False", "False", "False", "False" UNION
   SELECT "7/24/2018 19:51:28", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "False", "False", "False", "False" UNION
   SELECT "7/24/2018 19:54:25", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False" UNION
   SELECT "7/24/2018 19:55:35", "True" , "True" , "False", "False", "False", "False", "True" , "False", "True" , "False", "False", "True" , "False", "False" UNION
   SELECT "7/24/2018 20:04:56", "False", "False", "True" , "True" , "False", "False", "True" , "False", "True" , "False", "False", "True" , "False", "True"  UNION
   SELECT "7/24/2018 20:05:35", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False" UNION
   SELECT "7/24/2018 20:11:09", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "7/24/2018 20:21:55", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "7/24/2018 20:26:34", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False" UNION
   SELECT "7/24/2018 20:30:22", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "7/24/2018 20:37:13", "False", "True" , "True" , "False", "False", "False", "True" , "True" , "True" , "False", "True" , "True" , "False", "False" UNION
   SELECT "7/24/2018 20:38:40", "True" , "True" , "True" , "True" , "True" , "True" , "False", "False", "False", "False", "False", "True" , "False", "False" UNION
   SELECT "7/24/2018 20:41:20", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "7/24/2018 20:52:25", "False", "False", "False", "True" , "True" , "True" , "False", "True" , "False", "False", "True" , "False", "True" , "False" UNION
   SELECT "7/24/2018 20:53:11", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/24/2018 20:58:24", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False" UNION
   SELECT "7/24/2018 21:01:28", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/24/2018 21:03:51", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "7/24/2018 21:07:42", "False", "False", "True" , "True" , "False", "True" , "False", "True" , "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/24/2018 21:12:33", "True" , "True" , "True" , "True" , "False", "True" , "False", "True" , "False", "True" , "False", "True" , "True" , "False" UNION
   SELECT "7/24/2018 21:16:36", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "True" , "True" , "False", "True"  UNION
   SELECT "7/24/2018 22:23:59", "True" , "False", "True" , "False", "True" , "False", "True" , "False", "True" , "False", "False", "True" , "True" , "False" UNION
   SELECT "7/24/2018 22:28:01", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "True" , "False" UNION
   SELECT "7/24/2018 22:33:18", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "True" , "True" , "True" , "True"  UNION
   SELECT "7/24/2018 22:42:01", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "7/24/2018 22:43:02", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/24/2018 22:49:21", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/24/2018 22:51:39", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "7/24/2018 22:53:50", "False", "False", "True" , "True" , "False", "False", "False", "True" , "False", "True" , "False", "False", "False", "False" UNION
   SELECT "7/24/2018 23:10:48", "False", "True" , "False", "False", "False", "False", "True" , "False", "True" , "False", "True" , "True" , "False", "False" UNION
   SELECT "7/24/2018 23:58:30", "False", "False", "False", "True" , "False", "False", "True" , "False", "False", "True" , "False", "False", "True" , "False" UNION
   SELECT "7/25/2018 0:13:52" , "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "True" , "False" UNION
   SELECT "7/25/2018 0:37:35" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False" UNION
   SELECT "7/25/2018 0:45:00" , "False", "False", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "7/25/2018 0:50:53" , "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "True" , "True" , "False", "False" UNION
   SELECT "7/25/2018 1:08:51" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "False", "True" , "False", "False" UNION
   SELECT "7/25/2018 1:09:27" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False" UNION
   SELECT "7/25/2018 1:41:00" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "7/25/2018 2:12:26" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "7/25/2018 8:17:05" , "False", "False", "True" , "False", "True" , "False", "False", "False", "True" , "False", "True" , "True" , "False", "False" UNION
   SELECT "7/25/2018 8:39:18" , "False", "True" , "False", "True" , "False", "True" , "False", "True" , "False", "True" , "False", "False", "False", "True"  UNION
   SELECT "7/25/2018 9:29:21" , "False", "False", "False", "True" , "False", "True" , "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "7/25/2018 10:14:26", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False" UNION
   SELECT "7/25/2018 10:24:48", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False" UNION
   SELECT "7/25/2018 10:32:10", "False", "False", "False", "True" , "False", "True" , "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "7/25/2018 11:13:27", "True" , "False", "True" , "True" , "True" , "False", "True" , "True" , "True" , "True" , "True" , "False", "True" , "True"  UNION
   SELECT "7/25/2018 11:13:44", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "7/25/2018 11:14:04", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "7/25/2018 11:14:07", "False", "False", "True" , "True" , "False", "True" , "False", "True" , "False", "False", "False", "False", "False", "True"  UNION
   SELECT "7/25/2018 11:17:22", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "True" , "True" , "True" , "False", "False" UNION
   SELECT "7/25/2018 11:20:28", "True" , "False", "False", "True" , "False", "False", "True" , "False", "False", "True" , "False", "False", "True" , "False" UNION
   SELECT "7/25/2018 11:24:51", "False", "False", "False", "False", "True" , "False", "False", "True" , "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/25/2018 11:26:56", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "7/25/2018 11:45:14", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "True" , "True"  UNION
   SELECT "7/25/2018 12:15:46", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/25/2018 12:24:41", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/25/2018 12:47:09", "True" , "True" , "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "True" , "True"  UNION
   SELECT "7/25/2018 12:57:02", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False" UNION
   SELECT "7/25/2018 13:11:41", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "7/25/2018 13:20:26", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/25/2018 13:36:25", "False", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "7/25/2018 13:48:12", "True" , "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/25/2018 16:06:32", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False" UNION
   SELECT "7/25/2018 16:14:12", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "True" , "False", "False" UNION
   SELECT "7/25/2018 19:29:20", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "True" , "False" UNION
   SELECT "7/25/2018 20:21:35", "False", "False", "False", "False", "False", "False", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "False" UNION
   SELECT "7/25/2018 21:00:42", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "7/25/2018 21:27:51", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False" UNION
   SELECT "7/25/2018 22:52:08", "False", "False", "False", "False", "False", "True" , "False", "False", "True" , "False", "False", "False", "False", "False" UNION
   SELECT "7/26/2018 2:32:13" , "False", "False", "False", "True" , "False", "True" , "False", "False", "False", "False", "True" , "True" , "False", "False" UNION
   SELECT "7/26/2018 9:56:55" , "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "True" , "False", "False" UNION
   SELECT "7/26/2018 10:02:57", "False", "False", "True" , "False", "False", "False", "False", "False", "True" , "False", "False", "True" , "False", "False" UNION
   SELECT "7/26/2018 10:05:29", "False", "False", "False", "False", "True" , "False", "False", "True" , "False", "True" , "True" , "False", "True" , "False" UNION
   SELECT "7/26/2018 10:10:34", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/26/2018 11:13:39", "False", "True" , "False", "False", "False", "True" , "False", "False", "True" , "False", "False", "False", "True" , "False" UNION
   SELECT "7/26/2018 11:14:26", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "7/26/2018 11:14:31", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/26/2018 11:14:33", "True" , "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "7/26/2018 11:14:33", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "7/26/2018 11:14:37", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False" UNION
   SELECT "7/26/2018 11:14:40", "True" , "False", "True" , "False", "True" , "False", "True" , "False", "True" , "False", "True" , "True" , "True" , "False" UNION
   SELECT "7/26/2018 11:15:11", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "7/26/2018 11:15:53", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "True" , "False" UNION
   SELECT "7/26/2018 11:16:08", "True" , "False", "True" , "True" , "False", "True" , "True" , "True" , "False", "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "7/26/2018 11:17:05", "True" , "False", "True" , "False", "True" , "False", "True" , "False", "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "7/26/2018 11:21:16", "False", "False", "False", "False", "False", "True" , "False", "True" , "False", "False", "False", "True" , "True" , "True"  UNION
   SELECT "7/26/2018 11:36:00", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/26/2018 12:49:17", "True" , "True" , "True" , "False", "False", "False", "False", "False", "True" , "True" , "False", "True" , "True" , "True"  UNION
   SELECT "7/26/2018 12:52:42", "False", "False", "True" , "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/26/2018 13:36:03", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/26/2018 16:14:57", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "7/26/2018 16:43:16", "True" , "True" , "True" , "True" , "False", "True" , "False", "True" , "False", "False", "False", "False", "False", "True"  UNION
   SELECT "7/26/2018 17:01:17", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/26/2018 18:05:51", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/26/2018 19:45:04", "False", "True" , "False", "False", "False", "True" , "False", "True" , "False", "False", "False", "True" , "False", "False" UNION
   SELECT "7/26/2018 22:16:58", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/26/2018 22:19:25", "True" , "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "True"  UNION
   SELECT "7/27/2018 11:10:29", "False", "False", "True" , "True" , "True" , "False", "False", "True" , "False", "False", "True" , "True" , "True" , "True"  UNION
   SELECT "7/27/2018 14:35:52", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False" UNION
   SELECT "7/27/2018 18:08:55", "True" , "False", "False", "False", "False", "False", "False", "False", "True" , "True" , "False", "True" , "False", "False" ;